# INFO
# For ckpts >= opensr-model version 1.0, disable 'apply_normalization'
# For ckpts >= opensr-model version 1.0, set linear_start to 0.0001 and linear_end to 0.01
# For ckpts <  opensr-model version 1.0, set linear_start to and linear_end to 0.0015 and 0.0155 respectively

# WARNING: Some of the settings  are not used in the current version of opensr-model but are kept for backwards compatibility

# General Settings
apply_normalization: False
ckpt_version: "opensr-ldsrs2_v1_0_0.ckpt"
encode_conditioning: True
batch_size: 1

# Diffusion and Sampling Settings
denoiser_settings:
  linear_start: 0.0001 # noise start
  linear_end: 0.0155 # noise end
  timesteps: 1000 # Timesteps model was trained on - always 1k
  parameterization: "eps" # ["eps" or "x0"]
  sampling_eta: 0.95 # 0. to 1. -> 1 is more deterministic
  sampling_temperature: 1.0 # 0. to 1.
  sampling_steps: 100 # No of DDIM sampling steps

# Autoencoder Settings
first_stage_config:
  embed_dim: 4
  double_z: true
  z_channels: 4
  resolution: 512
  in_channels: 4
  out_ch: 4
  ch: 128
  ch_mult: [1, 2, 4]
  num_res_blocks: 2
  attn_resolutions: []
  dropout: 0.0

# Denoising UNet Settings
cond_stage_config:
  image_size: 128
  in_channels: 8
  model_channels: 160
  out_channels: 4
  num_res_blocks: 2
  attention_resolutions: [16, 8]
  channel_mult: [1, 2, 2, 4]
  num_head_channels: 32

# other settings
other:
  concat_mode: True
  cond_stage_trainable: False
  first_stage_key: "image"
  cond_stage_key: "LR_image"
